export const EnglishLocale = {
    MAILSENTMESSAGE:"Thank you for your email, we will contact you soon..",
    BABYLONHOLIDAYS: "Babylon Holidays",
    BABYLON: "Babylon",
    HOLIDAYS:"Holidays",
    HOME: "HOME",
    TOURS: "TOURS",
    SERVICES: "SERVICES",
    CONTACTUS:"CONTACT US",
    INDIVIDUAL:"INDIVIDUAL",
    HONEYMOON:"HONEYMOON",
    GROUP:"GROUP",
    DISCOVERTHEBEAUTY:"discover the beauty of our world",
    OF:"of",
    BALI:"Bali",
    BOOKATOUR:"Book a tour",
    OURTOUR:"Our Tour",
    ATTRACTIONSINBALI:"Attractions in Bali",
    FORMNAME:"NAME",
    FORMEMAIL:"EMAIL",
    FORMSUBJECT:"SUBJECT",
    FORMMESSAGE:"MESSAGE",
    FORMSUBMIT:"SUBMIT",
    WHEREDOYOUWANTTOSTAY:"WHERE DO YOU WANT TO STAY?",
    HOTEL:"HOTEL",
    VILLA:"VILLA",
    FIVESTAR:"5 STAR",
    FOURSTAR:"4 STAR",
    THREESTAR:"3 STAR",
    GROUPTOURS:"GROUP TOURS",
    NOOFDAYS:"# OF DAYS",
    NOOFPERSONS:"# OF PERSONS",
    WHENDOYOUWANTTOTRAVEL:"WHEN DO YOU WANT TO TRAVEL?",
    FROM:"FROM",
    TO:"TO",
    CONACTINFORMATION:"CONTACT INFORMATION",
    PHONENUMBER:"PHONE #",
    HONEYMOONTOURS:"HONEYMOON TOURS",
    STAYATHOTEL:"STAY AT HOTEL",
    SEEDETAILS:"SEE DETAILS",
    STANDARD:"STANDARD",
    PREMIUM:"PREMIUM",
    LUXURY:"LUXURY",
    STAYATVILLA:"STAY AT VILLA",
    INDIVIDUALTOURS:"INDIVIDUAL TOURS",
    HIGHLIGHTS:"HIGHLIGHTS",
    HONEYMOONSUITAT5STARHOTEL:"HONEYMOON SUIT AT 5 STAR HOTEL",
    DAYS7NIGHTS6:"7 DAYS 6 NIGHTS",
    BREAKFASTDINNER:"BREAKFAST & DINNER",
    COMFORTABLECARWITHDRIVER:"COMFORTABLE CAR WITH DRIVER",
    TRANSPORT:"TRANSPORT",
    BOOKNOW:"BOOK NOW",
    ENQUIRENOW:"ENQUIRE NOW",
    ADDRESS:"ADDRESS",
    PHONE:"PHONE",
    LANGUAGE:"لغة",
    ARABIC:"ARABIC",
    ENGLISH:"English",
    INDONESIA:"INDONESIA",
    GILIS:"GILIS",
    LOMBOK:"LOMBOK",
    JAKARTA:"JAKARTA",
    PUNCAK:"PUNCAK",
    BANDUNG:"BANDUNG",
    KOMODO:"KOMODO",
    DISTINCTION:"DESTINATIONS",
    DESTINATIONS:"DESTINATIONS",
    WHYCHOOSEUS :"WHY CHOOSE US",
    HANDPICKHOTEL: "Handpicked Hotel",
    WORLDCLASSSERVICE: "World Class Service",
    BESTPRICEGURANTEE : "Best Price Guarantee",
    CATEGORY: "Category",
    DESCRIPTION: "Description",
    ITINERARY:"Itinerary",
    LOCATION:"Location",
    AIRFARE:"Airfare",
    DAY:"Day",
    DEPARTURE:"Departure",
    RETURN:"Return",
    BALITOORS:"BALI TOURS",
    BANDUNGTOORS:"BANDUNG TOURS",
    GILISTOORS:"GILIS TOURS",
    JAKARTATOORS:"JAKARTA TOURS",
    KOMODOTOORS:"KOMODO TOURS",
    LOMBOKTOORS:"LOMBOK TOURS",
    PUNCAKTOORS:"PUNCAK TOURS",
    HAVEAQUESTION:"HAVE A QUESTION?",
    QUESTION: "Question",
    SCROLLDOWN: "Scroll",

   /***************************************INDIVIDUAL PAGE *****************************************************/
    INDIVIDUAL_TITLE:"Discover Bali",
    INDIVIDUAL_STAY_TIME:"5 DAYS - 4 NIGHTS",
    INIDVIDUAL_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
    INIDIVIDUAL_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
    INIDIVIDUAL_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
    INIDIVIDUAL_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
    INIDIVIDUAL_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
    INDIVIDUAL_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
    INDIVIDUAL_DAY_1_DEP_2  : "Maecenas massa. Fermentum.",
    INDIVIDUAL_DAY_1_DEP_P1 : "Pretium vitae tempus sem enim enim.",
    INDIVIDUAL_DAY_1_DEP_P2 : "Tempus, leo, taciti augue aliquam hendrerit.",
    INDIVIDUAL_DAY_1_DEP_P3 : "Accumsan pharetra eros justo augue posuere felis elit cras montes fames.",
    INDIVIDUAL_DAY_1_DEP_P4 : "Vulputate dictumst egestas etiam dictum varius.",
    INDIVIDUAL_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
    INDIVIDUAL_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
    INDIVIDUAL_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
    INDIVIDUAL_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
    INDIVIDUAL_TABLE_H1: "DEPARTURE/RETURN LOCATION",
    INDIVIDUAL_TABLE_H2: "DEPARTURE TIME",
    INDIVIDUAL_TABLE_H3: "INCLUDED",
    INDIVIDUAL_TABLE_H4: "NOT INCLUDED",
    INDIVIDUAL_TABLE_H1D  : "San Francisco International Airport",
    INDIVIDUAL_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
    INDIVIDUAL_TABLE_H3D1 : "Airfare",
    INDIVIDUAL_TABLE_H3D2 : "Accommodations",
    INDIVIDUAL_TABLE_H3D3 : "2 days cruise	",
    INDIVIDUAL_TABLE_H3D4 : "Professional guide",
    INDIVIDUAL_TABLE_H4D1 : "Entrance fees",
    INDIVIDUAL_TABLE_H4D2 : "Professional guide",

   /************************************************************************************************************/
   BALI_1_TITLE:"Hello to the fairy World.",
   BALI_1_STAY: "6 days 7 nights",
   BALI_1_DESCRIPTION: "",
   BALI_1_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   BALI_2_TITLE:"Hello to the fairy World.",
   BALI_2_STAY: "6 days 7 nights",
   BALI_2_DESCRIPTION: "",
   BALI_2_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   BALI_3_TITLE:"Hello to the fairy World.",
   BALI_3_STAY: "6 days 7 nights",
   BALI_3_DESCRIPTION: "",
   BALI_3_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   BALI_4_TITLE:"Hello to the fairy World.",
   BALI_4_STAY: "6 days 7 nights",
   BALI_4_DESCRIPTION: "",
   BALI_4_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   LOMBOK_1_TITLE:"Hello to the fairy World.",
   LOMBOK_1_STAY: "6 days 7 nights",
   LOMBOK_1_DESCRIPTION: "",
   LOMBOK_1_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   LOMBOK_2_TITLE:"Hello to the fairy World.",
   LOMBOK_2_STAY: "6 days 7 nights",
   LOMBOK_2_DESCRIPTION: "",
   LOMBOK_2_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   LOMBOK_3_TITLE:"Hello to the fairy World.",
   LOMBOK_3_STAY: "6 days 7 nights",
   LOMBOK_3_DESCRIPTION: "",
   LOMBOK_3_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   JAKARTA_1_TITLE:"Hello to the fairy World.",
   JAKARTA_1_STAY: "6 days 7 nights",
   JAKARTA_1_DESCRIPTION: "",
   JAKARTA_1_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   JAKARTA_2_TITLE:"Hello to the fairy World.",
   JAKARTA_2_STAY: "6 days 7 nights",
   JAKARTA_2_DESCRIPTION: "",
   JAKARTA_2_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   JAKARTA_3_TITLE:"Hello to the fairy World.",
   JAKARTA_3_STAY: "6 days 7 nights",
   JAKARTA_3_DESCRIPTION: "",
   JAKARTA_3_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   PUNCAK_1_TITLE:"Hello to the fairy World.",
   PUNCAK_1_STAY: "6 days 7 nights",
   PUNCAK_1_DESCRIPTION: "",
   PUNCAK_1_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   PUNCAK_2_TITLE:"Hello to the fairy World.",
   PUNCAK_2_STAY: "6 days 7 nights",
   PUNCAK_2_DESCRIPTION: "",
   PUNCAK_2_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   PUNCAK_3_TITLE:"Hello to the fairy World.",
   PUNCAK_3_STAY: "6 days 7 nights",
   PUNCAK_3_DESCRIPTION: "",
   PUNCAK_3_DETAIL:"to the vast place where no one can detect the benifit of this economy",

   BANDUNG_1_TITLE:"Hello to the fairy World.",
   BANDUNG_1_STAY: "6 days 7 nights",
   BANDUNG_1_DESCRIPTION: "",
   BANDUNG_1_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   BANDUNG_2_TITLE:"Hello to the fairy World.",
   BANDUNG_2_STAY: "6 days 7 nights",
   BANDUNG_2_DESCRIPTION: "",
   BANDUNG_2_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   BANDUNG_3_TITLE:"Hello to the fairy World.",
   BANDUNG_3_STAY: "6 days 7 nights",
   BANDUNG_3_DESCRIPTION: "",
   BANDUNG_3_DETAIL:"to the vast place where no one can detect the benifit of this economy",

   KOMODO_1_TITLE:"Hello to the fairy World.",
   KOMODO_1_STAY: "6 days 7 nights",
   KOMODO_1_DESCRIPTION: "",
   KOMODO_1_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   KOMODO_2_TITLE:"Hello to the fairy World.",
   KOMODO_2_STAY: "6 days 7 nights",
   KOMODO_2_DESCRIPTION: "",
   KOMODO_2_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   KOMODO_3_TITLE:"Hello to the fairy World.",
   KOMODO_3_STAY: "6 days 7 nights",
   KOMODO_3_DESCRIPTION: "",
   KOMODO_3_DETAIL:"to the vast place where no one can detect the benifit of this economy",
}

export const ArabicLocale = {

    QUESTION: "Question",
    HAVEAQUESTION:"HAVE A QUESTION?",
    MAILSENTMESSAGE:"Thank you for your email, we will contact you soon..",
    BABYLONHOLIDAYS: "بابيلون للسياحة والسفر",
    BABYLON: "Babylon",
    HOLIDAYS:"Holidays",
    HANDPICKHOTEL: "Handpicked Hotel",
    WORLDCLASSSERVICE: "World Class Service",
    BESTPRICEGURANTEE : "Best Price Guarantee",
    WHYCHOOSEUS :"WHY CHOOSE US",
    HOME: "الصفحة الرئيسية",
    TOURS: "جولات",
    SERVICES: "خدمات",
    CONTACTUS:"اتصل بنا",
    INDIVIDUAL:"فرد",
    HONEYMOON:"شهر العسل",
    GROUP:"مجموعة",
    DISCOVERTHEBEAUTY:"اكتشف الجمال",
    OF:"من",
    BALI:"بالي",
    BOOKATOUR:"حجز جولة",
    OURTOUR:"جولتنا",
    ATTRACTIONSINBALI:"الجذب السياحي في بالي",
    FORMNAME:"اسم",
    FORMEMAIL:"البريد الإلكتروني",
    FORMSUBJECT:"موضوع",
    FORMMESSAGE:"رسالة",
    FORMSUBMIT:"خضع",
    WHEREDOYOUWANTTOSTAY:"أين تريد أن تبقى؟",
    HOTEL:"الفندق",
    VILLA:"فيلا",
    FIVESTAR:"5 نجوم",
    FOURSTAR:"4 نجوم",
    THREESTAR:"3 نجوم",
    GROUPTOURS:"جولات المجموعة",
    NOOFDAYS:"# أيام",
    NOOFPERSONS:"عدد الأشخاص",
    WHENDOYOUWANTTOTRAVEL:"عندما تريد السفر؟",
    FROM:"من عند",
    TO:"إلى",
    CONACTINFORMATION:"معلومات الاتصال",
    PHONENUMBER:"هاتف #",
    HONEYMOONTOURS:" جولات شهر العسل",
    STAYATHOTEL:"البقاء في فندق",
    SEEDETAILS:"انظر التفاصيل",
    STANDARD:"اساسي",
    PREMIUM:"علاوة",
    LUXURY:"ترف",
    STAYATVILLA:"البقاء في فيلا",
    INDIVIDUALTOURS:"جولات فردية",
    HIGHLIGHTS:"يسلط الضوء",
    HONEYMOONSUITAT5STARHOTEL:"جناح شهر العسل في فندق 5 نجوم",
    DAYS7NIGHTS6:"7 أيام 6 ليالي",
    BREAKFASTDINNER:"وجبة الإفطار & العشاء",
    COMFORTABLECARWITHDRIVER:"سيارة مريحة مع سائق",
    TRANSPORT:"المواصلات",
    BOOKNOW:"احجز الآن",
    ENQUIRENOW:"استفسر الان",
    ADDRESS:"عنوان",
    PHONE:"هاتف",
    LANGUAGE:"Language",
    ARABIC:"عربى",
    ENGLISH:"الإنجليزية",
    INDONESIA:"أندونيسيا",
    GILIS:"جيليس",
    LOMBOK:"لومبوك",
    JAKARTA:"جاكرتا",
    PUNCAK:"بونكاك",
    DISTINCTION:"تميز",
    DESTINATIONS:"تميز",
    CATEGORY:"الفئة",
    BALITOORS:"BALI TOURS",
    BANDUNGTOORS:"BANDUNG TOURS",
    GILISTOORS:"GILIS TOURS",
    JAKARTATOORS:"JAKARTA TOURS",
    KOMODOTOORS:"KOMODO TOURS",
    LOMBOKTOORS:"LOMBOK TOURS",
    PUNCAKTOORS:"PUNCAK TOURS",

    SCROLLDOWN: "Scroll",


   /***************************************INDIVIDUAL PAGE *****************************************************/
    INDIVIDUAL_TITLE:"Discover Bali",
    INDIVIDUAL_STAY_TIME:"5 DAYS - 4 NIGHTS",
    INIDVIDUAL_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
    INIDIVIDUAL_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
    INIDIVIDUAL_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
    INIDIVIDUAL_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
    INIDIVIDUAL_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
    INDIVIDUAL_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
    INDIVIDUAL_DAY_1_DEP_2  : "Maecenas massa. Fermentum.",
    INDIVIDUAL_DAY_1_DEP_P1 : "Pretium vitae tempus sem enim enim.",
    INDIVIDUAL_DAY_1_DEP_P2 : "Tempus, leo, taciti augue aliquam hendrerit.",
    INDIVIDUAL_DAY_1_DEP_P3 : "Accumsan pharetra eros justo augue posuere felis elit cras montes fames.",
    INDIVIDUAL_DAY_1_DEP_P4 : "Vulputate dictumst egestas etiam dictum varius.",
    INDIVIDUAL_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
    INDIVIDUAL_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
    INDIVIDUAL_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
    INDIVIDUAL_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
    INDIVIDUAL_TABLE_H1: "DEPARTURE/RETURN LOCATION",
    INDIVIDUAL_TABLE_H2: "DEPARTURE TIME",
    INDIVIDUAL_TABLE_H3: "INCLUDED",
    INDIVIDUAL_TABLE_H4: "NOT INCLUDED",
    INDIVIDUAL_TABLE_H1D  : "San Francisco International Airport",
    INDIVIDUAL_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
    INDIVIDUAL_TABLE_H3D1 : "Airfare",
    INDIVIDUAL_TABLE_H3D2 : "Accommodations",
    INDIVIDUAL_TABLE_H3D3 : "2 days cruise	",
    INDIVIDUAL_TABLE_H3D4 : "Professional guide",
    INDIVIDUAL_TABLE_H4D1 : "Entrance fees",
    INDIVIDUAL_TABLE_H4D2 : "Professional guide",

   /************************************************************************************************************/

   BALI_1_TITLE:"Hello to the fairy World.",
   BALI_1_STAY: "6 days 7 nights",
   BALI_1_DESCRIPTION: "",
   BALI_1_DETAIL:"سيارة مريحة مع سائق",
   BALI_2_TITLE:"Hello to the fairy World.",
   BALI_2_STAY: "6 days 7 nights",
   BALI_2_DESCRIPTION: "",
   BALI_2_DETAIL:"سيارة مريحة مع سائق",
   BALI_3_TITLE:"Hello to the fairy World.",
   BALI_3_STAY: "6 days 7 nights",
   BALI_3_DESCRIPTION: "",
   BALI_3_DETAIL:"سيارة مريحة مع سائق",
   BALI_4_TITLE:"Hello to the fairy World.",
   BALI_4_STAY: "6 days 7 nights",
   BALI_4_DESCRIPTION: "",
   BALI_4_DETAIL:"سيارة مريحة مع سائق",
   LOMBOK_1_TITLE:"Hello to the fairy World.",
   LOMBOK_1_STAY: "6 days 7 nights",
   LOMBOK_1_DESCRIPTION: "",
   LOMBOK_1_DETAIL:"سيارة مريحة مع سائق",
   LOMBOK_2_TITLE:"Hello to the fairy World.",
   LOMBOK_2_STAY: "6 days 7 nights",
   LOMBOK_2_DESCRIPTION: "",
   LOMBOK_2_DETAIL:"سيارة مريحة مع سائق",
   LOMBOK_3_TITLE:"Hello to the fairy World.",
   LOMBOK_3_STAY: "6 days 7 nights",
   LOMBOK_3_DESCRIPTION: "",
   LOMBOK_3_DETAIL:"سيارة مريحة مع سائق",
   JAKARTA_1_TITLE:"Hello to the fairy World.",
   JAKARTA_1_STAY: "6 days 7 nights",
   JAKARTA_1_DESCRIPTION: "",
   JAKARTA_1_DETAIL:"سيارة مريحة مع سائق",
   JAKARTA_2_TITLE:"Hello to the fairy World.",
   JAKARTA_2_STAY: "6 days 7 nights",
   JAKARTA_2_DESCRIPTION: "",
   JAKARTA_2_DETAIL:"سيارة مريحة مع سائق",
   JAKARTA_3_TITLE:"Hello to the fairy World.",
   JAKARTA_3_STAY: "6 days 7 nights",
   JAKARTA_3_DESCRIPTION: "",
   JAKARTA_3_DETAIL:"سيارة مريحة مع سائق",
   PUNCAK_1_TITLE:"Hello to the fairy World.",
   PUNCAK_1_STAY: "6 days 7 nights",
   PUNCAK_1_DESCRIPTION: "",
   PUNCAK_1_DETAIL:"سيارة مريحة مع سائق",
   PUNCAK_2_TITLE:"Hello to the fairy World.",
   PUNCAK_2_STAY: "6 days 7 nights",
   PUNCAK_2_DESCRIPTION: "",
   PUNCAK_2_DETAIL:"سيارة مريحة مع سائق",
   PUNCAK_3_TITLE:"Hello to the fairy World.",
   PUNCAK_3_STAY: "6 days 7 nights",
   PUNCAK_3_DESCRIPTION: "",
   PUNCAK_3_DETAIL:"سيارة مريحة مع سائق",

   BANDUNG_1_TITLE:"Hello to the fairy World.",
   BANDUNG_1_STAY: "6 days 7 nights",
   BANDUNG_1_DESCRIPTION: "",
   BANDUNG_1_DETAIL:"سيارة مريحة مع سائق",
   BANDUNG_2_TITLE:"Hello to the fairy World.",
   BANDUNG_2_STAY: "6 days 7 nights",
   BANDUNG_2_DESCRIPTION: "",
   BANDUNG_2_DETAIL:"سيارة مريحة مع سائق",
   BANDUNG_3_TITLE:"Hello to the fairy World.",
   BANDUNG_3_STAY: "6 days 7 nights",
   BANDUNG_3_DESCRIPTION: "",
   BANDUNG_3_DETAIL:"سيارة مريحة مع سائق",

   KOMODO_1_TITLE:"Hello to the fairy World.",
   KOMODO_1_STAY: "6 days 7 nights",
   KOMODO_1_DESCRIPTION: "",
   KOMODO_1_DETAIL:"سيارة مريحة مع سائق",
   KOMODO_2_TITLE:"Hello to the fairy World.",
   KOMODO_2_STAY: "6 days 7 nights",
   KOMODO_2_DESCRIPTION: "",
   KOMODO_2_DETAIL:"سيارة مريحة مع سائق",
   KOMODO_3_TITLE:"Hello to the fairy World.",
   KOMODO_3_STAY: "6 days 7 nights",
   KOMODO_3_DESCRIPTION: "",
   KOMODO_3_DETAIL:"سيارة مريحة مع سائق",
}
