export const EnglishLocale = {
    HOME: "HOME",
    TOURS: "TOURS",
    SERVICES: "SERVICES",
    CONTACTUS:"CONTACT US",
    INDIVIDUAL:"INDIVIDUAL",
    HONEYMOON:"HONEYMOON",
    GROUP:"GROUP",
    DISCOVERTHEBEAUTY:"discover the beauty",
    OF:"of",
    BALI:"Bali",
    BOOKATOUR:"Book a tour",
    OURTOUR:"Our Tour",
    ATTRACTIONSINBALI:"Attractions in Bali",
    FORMNAME:"NAME",
    FORMEMAIL:"EMAIL",
    FORMSUBJECT:"SUBJECT",
    FORMMESSAGE:"MESSAGE",
    FORMSUBMIT:"SUBMIT",
    WHEREDOYOUWANTTOSTAY:"WHERE DO YOU WANT TO STAY?",
    HOTEL:"HOTEL",
    VILLA:"VILLA",
    FIVESTAR:"5 STAR",
    FOURSTAR:"4 STAR",
    THREESTAR:"3 STAR",
    GROUPTOURS:"GROUP TOURS",
    NOOFDAYS:"# OF DAYS",
    NOOFPERSONS:"# OF PERSONS",
    WHENDOYOUWANTTOTRAVEL:"WHEN DO YOU WANT TO TRAVEL?",
    FROM:"FROM",
    TO:"TO",
    CONACTINFORMATION:"CONTACT INFORMATION",
    PHONENUMBER:"PHONE #",
    HONEYMOONTOURS:"HONEYMOON TOURS",
    STAYATHOTEL:"STAY AT HOTEL",
    SEEDETAILS:"SEE DETAILS",
    STANDARD:"STANDARD",
    PREMIUM:"PREMIUM",
    LUXURY:"LUXURY",
    STAYATVILLA:"STAY AT VILLA",
    INDIVIDUALTOURS:"INDIVIDUAL TOURS",
    HIGHLIGHTS:"HIGHLIGHTS",
    HONEYMOONSUITAT5STARHOTEL:"HONEYMOON SUIT AT 5 STAR HOTEL",
    DAYS7NIGHTS6:"7 DAYS 6 NIGHTS",
    BREAKFASTDINNER:"BREAKFAST & DINNER",
    COMFORTABLECARWITHDRIVER:"COMFORTABLE CAR WITH DRIVER",
    TRANSPORT:"TRANSPORT",
    BOOKNOW:"BOOK NOW",
    ENQUIRENOW:"ENQUIRE NOW",
    ADDRESS:"ADDRESS",
    PHONE:"PHONE",
    LANGUAGE:"لغة",
    ARABIC:"ARABIC",
    ENGLISH:"English",
    INDONESIA:"INDONESIA",
    GILIS:"GILIS",
    LOMBOK:"LOMBOK",
    JAKARTA:"JAKARTA",
    PUNCAK:"PUNCAK",
    DISTINCTION:"DISTINCTION",
    DESTINATIONS:"DESTINATIONS",
    WHYCHOOSEUS :"WHY CHOOSE US",
    HANDPICKHOTEL: "Handpicked Hotel",
    WORLDCLASSSERVICE: "World Class Service",
    BESTPRICEGURANTEE : "Best Price Guarantee",
}

export const ArabicLocale = {
    HANDPICKHOTEL: "Handpicked Hotel",
    WORLDCLASSSERVICE: "World Class Service",
    BESTPRICEGURANTEE : "Best Price Guarantee",
    WHYCHOOSEUS :"WHY CHOOSE US",
    HOME: "الصفحة الرئيسية",
    TOURS: "جولات",
    SERVICES: "خدمات",
    CONTACTUS:"اتصل بنا",
    INDIVIDUAL:"فرد",
    HONEYMOON:"شهر العسل",
    GROUP:"مجموعة",
    DISCOVERTHEBEAUTY:"اكتشف الجمال",
    OF:"من",
    BALI:"بالي",
    BOOKATOUR:"حجز جولة",
    OURTOUR:"جولتنا",
    ATTRACTIONSINBALI:"الجذب السياحي في بالي",
    FORMNAME:"اسم",
    FORMEMAIL:"البريد الإلكتروني",
    FORMSUBJECT:"موضوع",
    FORMMESSAGE:"رسالة",
    FORMSUBMIT:"خضع",
    WHEREDOYOUWANTTOSTAY:"أين تريد أن تبقى؟",
    HOTEL:"الفندق",
    VILLA:"فيلا",
    FIVESTAR:"5 نجوم",
    FOURSTAR:"4 نجوم",
    THREESTAR:"3 نجوم",
    GROUPTOURS:"جولات المجموعة",
    NOOFDAYS:"# أيام",
    NOOFPERSONS:"عدد الأشخاص",
    WHENDOYOUWANTTOTRAVEL:"عندما تريد السفر؟",
    FROM:"من عند",
    TO:"إلى",
    CONACTINFORMATION:"معلومات الاتصال",
    PHONENUMBER:"هاتف #",
    HONEYMOONTOURS:" جولات شهر العسل",
    STAYATHOTEL:"البقاء في فندق",
    SEEDETAILS:"انظر التفاصيل",
    STANDARD:"اساسي",
    PREMIUM:"علاوة",
    LUXURY:"ترف",
    STAYATVILLA:"البقاء في فيلا",
    INDIVIDUALTOURS:"جولات فردية",
    HIGHLIGHTS:"يسلط الضوء",
    HONEYMOONSUITAT5STARHOTEL:"جناح شهر العسل في فندق 5 نجوم",
    DAYS7NIGHTS6:"7 أيام 6 ليالي",
    BREAKFASTDINNER:"وجبة الإفطار & العشاء",
    COMFORTABLECARWITHDRIVER:"سيارة مريحة مع سائق",
    TRANSPORT:"المواصلات",
    BOOKNOW:"احجز الآن",
    ENQUIRENOW:"استفسر الان",
    ADDRESS:"عنوان",
    PHONE:"هاتف",
    LANGUAGE:"Language",
    ARABIC:"عربى",
    ENGLISH:"الإنجليزية",
    INDONESIA:"أندونيسيا",
    GILIS:"جيليس",
    LOMBOK:"لومبوك",
    JAKARTA:"جاكرتا",
    PUNCAK:"بونكاك",
    DISTINCTION:"تميز",
    DESTINATIONS:"تميز"
}
