export const EnglishLocale = {


    DESTINATIONSDETAIL: "Indonesia tourism is popular for fun, adventure and best holidaying tours. Babylon holidays provides different tour packages for you to go to beautiful places of Indonesia with great deals.Your happiness is our first priority, So if you are adventures and you love nature's beauty Babylon is the Best Brand for you.\nHere are some of the destinations",
    WHYCHOOSEUSDETAIL:"Our team of babylonholiday travel insiders are so passionate about finding new places and to do best things for tours everywhere. We travel to beautiful destination of Indonesia, from Jakarta to Bali, Puncake , Lombok , Komodo , Bandung and Gilis. All the staff and management in this company has more than twenty years' experience in the tourism industry.An excellent reputation for personal services, quality and value through extensive research and a comprehensive.\n\nwe are here for you, Come and book your tour with us for Indonesia travel!",
    HANDPICKHOTELDETAIL: "Enjoy your tours with our years of experience!\
      Our team of travel insiders handpicks the prestigious hotels for all the tours. We make sure\
      you always have an exceptional experience.",
    WORLDCLASSSERVICEDETAIL:"We are so concerned with giving you travel services online booking.\
        With babylonholidays team you can get Professional and customer-oriented consultation\
        which provide hassle free travel.",
    BESTPRICEGURANTEEDETAIL: "We make sure to provide you great deals with best price.\
        Great deal makes your trip fantastic. So, our prices are totally guarantee, we finalise it after\
        detailed market search. So, just relax and your wallet can also relax. Because It’s vacation\
        time!",
    DISCOVERBEAUTIDETAIL: "A best tour by great coach is a relaxing way of seeing various beautiful destinations as you will not have to drive but get driven while a competent travel tours guide will present the various sights and you will just have to listen.",
    MAILSENTMESSAGE:"Thank you for your email, we will contact you soon..",
    BABYLONHOLIDAYS: "Babylon Holidays",
    BABYLON: "Babylon",
    HOLIDAYS:"Holidays",
    HOME: "HOME",
    TOURS: "TOURS",
    SERVICES: "services",
    SERVICESLABEL: "Plan your next journey with us",
    CONTACTUS:"CONTACT US",
    INDIVIDUAL:"INDIVIDUAL",
    HONEYMOON:"HONEYMOON",
    GROUP:"GROUP",
    DISCOVERTHEBEAUTY:"discover the beauty of our world",
    OF:"of",
    BALI:"Bali",
    BOOKATOUR:"Book a tour",
    OURTOUR:"Indonasia Tours",
    ATTRACTIONSINBALI:"Discover the beauty of Indonesia",
    FORMNAME:"NAME",
    FORMEMAIL:"EMAIL",
    FORMSUBJECT:"SUBJECT",
    FORMMESSAGE:"MESSAGE",
    FORMSUBMIT:"SUBMIT",
    WHEREDOYOUWANTTOSTAY:"WHERE DO YOU WANT TO STAY?",
    HOTEL:"HOTEL",
    VILLA:"VILLA",
    FIVESTAR:"5 STAR",
    FOURSTAR:"4 STAR",
    THREESTAR:"3 STAR",
    GROUPTOURS:"GROUP TOURS",
    NOOFDAYS:"# OF DAYS",
    NOOFPERSONS:"# OF PERSONS",
    WHENDOYOUWANTTOTRAVEL:"WHEN DO YOU WANT TO TRAVEL?",
    FROM:"FROM",
    TO:"TO",
    CONACTINFORMATION:"CONTACT INFORMATION",
    PHONENUMBER:"PHONE #",
    HONEYMOONTOURS:"HONEYMOON TOURS",
    STAYATHOTEL:"STAY AT HOTEL",
    SEEDETAILS:"SEE DETAILS",
    STANDARD:"STANDARD",
    PREMIUM:"PREMIUM",
    LUXURY:"LUXURY",
    STAYATVILLA:"STAY AT VILLA",
    INDIVIDUALTOURS:"INDIVIDUAL TOURS",
    HIGHLIGHTS:"HIGHLIGHTS",
    HONEYMOONSUITAT5STARHOTEL:"HONEYMOON SUIT AT 5 STAR HOTEL",
    DAYS7NIGHTS6:"7 DAYS 6 NIGHTS",
    BREAKFASTDINNER:"BREAKFAST & DINNER",
    COMFORTABLECARWITHDRIVER:"COMFORTABLE CAR WITH DRIVER",
    TRANSPORT:"TRANSPORT",
    BOOKNOW:"BOOK NOW",
    ENQUIRENOW:"ENQUIRE NOW",
    ADDRESS:"ADDRESS",
    PHONE:"PHONE",
    LANGUAGE:"لغة",
    ARABIC:"ARABIC",
    ENGLISH:"English",
    INDONESIA:"INDONESIA",
    GILIS:"GILIS",
    LOMBOK:"LOMBOK",
    JAKARTA:"JAKARTA",
    PUNCAK:"PUNCAK",
    BANDUNG:"BANDUNG",
    KOMODO:"KOMODO",
    DISTINCTION:"DESTINATIONS",
    DESTINATIONS:"DESTINATIONS",
    WHYCHOOSEUS :"WHY CHOOSE US",
    HANDPICKHOTEL: "Handpicked Hotel",
    WORLDCLASSSERVICE: "World Class Service",
    BESTPRICEGURANTEE : "Best Price Guarantee",
    CATEGORY: "Category",
    DESCRIPTION: "Description",
    ITINERARY:"Itinerary",
    LOCATION:"Location",
    AIRFARE:"Airfare",
    DAY:"Day",
    DEPARTURE:"Departure",
    RETURN:"Return",
    BALITOORS:"BALI TOURS",
    BANDUNGTOORS:"BANDUNG TOURS",
    GILISTOORS:"GILIS TOURS",
    JAKARTATOORS:"JAKARTA TOURS",
    KOMODOTOORS:"KOMODO TOURS",
    LOMBOKTOORS:"LOMBOK TOURS",
    PUNCAKTOORS:"PUNCAK TOURS",
    HAVEAQUESTION:"HAVE A QUESTION?",
    QUESTION: "Question",
    SCROLLDOWN: "Scroll",
    INDIVIDUALTOUR: "INDIVIDUAL",
    HONEYMOONTOUR: "HONEYMOON",
    GROUPTOUR: "GROUP/FAMILY",

   /***************************************INDIVIDUAL PAGE *****************************************************/
    INDIVIDUAL_TITLE:"Discover Bali",
    INDIVIDUAL_STAY:"5 DAYS - 4 NIGHTS",
    INIDVIDUAL_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
    INIDIVIDUAL_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
    INIDIVIDUAL_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
    INIDIVIDUAL_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
    INIDIVIDUAL_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
    INDIVIDUAL_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
    INDIVIDUAL_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
    INDIVIDUAL_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
    INDIVIDUAL_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
    INDIVIDUAL_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
    INDIVIDUAL_TABLE_H1: "DEPARTURE/RETURN LOCATION",
    INDIVIDUAL_TABLE_H2: "DEPARTURE TIME",
    INDIVIDUAL_TABLE_H3: "INCLUDED",
    INDIVIDUAL_TABLE_H4: "NOT INCLUDED",
    INDIVIDUAL_TABLE_H1D  : "San Francisco International Airport",
    INDIVIDUAL_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
    INDIVIDUAL_TABLE_H3D1 : "Airfare",
    INDIVIDUAL_TABLE_H3D2 : "Accommodations",
    INDIVIDUAL_TABLE_H3D3 : "2 days cruise	",
    INDIVIDUAL_TABLE_H3D4 : "Professional guide",
    INDIVIDUAL_TABLE_H4D1 : "Entrance fees",
    INDIVIDUAL_TABLE_H4D2 : "Professional guide",

   /************************************************************************************************************/
   BALI_DETAIL:"Bali is known to be Indonesian paradise which is more like a fantasy and having best tour\n\
      places. Bali is very exciting place to visit individually as well as in a group. Amazing tour\
      packages and unique sightseeing opportunities you will find with us. People who are\
      passionate about adventure and excited tours can travel continuously in the scenic rural\
      countryside of beautiful Bali interiors, while those who are enthusiastic for history and\
      cultural discovery can travel whole day to the majestic temple of Bali.\
      Popular tours are started from various highlights like Island's eight regencies, cool uplands to\
      the crystals waters but we have narrow down our Bali tour packages to the best places of Bali\
      so you can plan accordingly. Let's book full day and night tours in Bali and share you\
      experiences with us. All packages details are mentioned: come and explore!",
   JAKARTA_DETAIL:"Jakatra is a Capital of Indonesia, is a city of contrasts like chaotic and crowded. Millions of\
      people are staying in this city from all over the world, the city is a mixture of different\
      cultures and languages. The city possesses some of the best nightlife in Asia and some of the\
      worst traffic too. So, for holidaying purpose people of Jakatra and from all over the world\
      move to different places of the city for relaxing and enjoyment. for example, Dreamland,\
      Museums, mosques beaches, water parks. Amazing Places to visit Jakarta read below.",
   BALI_1_TITLE:"Hello to the fairy World.",
   BALI_1_STAY: "6 days 7 nights",
   BALI_1_DESCRIPTION: "",
   BALI_1_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   BALI_1_TITLE:"Discover Bali",
   BALI_1_STAY:"5 DAYS - 4 NIGHTS",
   BALI_1_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   BALI_1_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   BALI_1_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   BALI_1_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   BALI_1_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   BALI_1_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   BALI_1_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   BALI_1_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   BALI_1_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   BALI_1_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   BALI_1_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   BALI_1_TABLE_H2: "DEPARTURE TIME",
   BALI_1_TABLE_H3: "INCLUDED",
   BALI_1_TABLE_H4: "NOT INCLUDED",
   BALI_1_TABLE_H1D  : "San Francisco International Airport",
   BALI_1_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   BALI_1_TABLE_H3D1 : "Airfare",
   BALI_1_TABLE_H3D2 : "Accommodations",
   BALI_1_TABLE_H3D3 : "2 days cruise	",
   BALI_1_TABLE_H3D4 : "Professional guide",
   BALI_1_TABLE_H4D1 : "Entrance fees",
   BALI_1_TABLE_H4D2 : "Professional guide",

   BALI_2_TITLE:"Hello to the fairy World.",
   BALI_2_STAY: "6 days 7 nights",
   BALI_2_DESCRIPTION: "",
   BALI_2_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   BALI_2_TITLE:"Discover Bali",
   BALI_2_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   BALI_2_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   BALI_2_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   BALI_2_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   BALI_2_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   BALI_2_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   BALI_2_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   BALI_2_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   BALI_2_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   BALI_2_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   BALI_2_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   BALI_2_TABLE_H2: "DEPARTURE TIME",
   BALI_2_TABLE_H3: "INCLUDED",
   BALI_2_TABLE_H4: "NOT INCLUDED",
   BALI_2_TABLE_H1D  : "San Francisco International Airport",
   BALI_2_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   BALI_2_TABLE_H3D1 : "Airfare",
   BALI_2_TABLE_H3D2 : "Accommodations",
   BALI_2_TABLE_H3D3 : "2 days cruise	",
   BALI_2_TABLE_H3D4 : "Professional guide",
   BALI_2_TABLE_H4D1 : "Entrance fees",
   BALI_2_TABLE_H4D2 : "Professional guide",

   BALI_3_TITLE:"Hello to the fairy World.",
   BALI_3_STAY: "6 days 7 nights",
   BALI_3_DESCRIPTION: "",
   BALI_3_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   BALI_3_TITLE:"Discover Bali",
   BALI_3_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   BALI_3_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   BALI_3_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   BALI_3_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   BALI_3_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   BALI_3_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   BALI_3_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   BALI_3_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   BALI_3_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   BALI_3_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   BALI_3_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   BALI_3_TABLE_H2: "DEPARTURE TIME",
   BALI_3_TABLE_H3: "INCLUDED",
   BALI_3_TABLE_H4: "NOT INCLUDED",
   BALI_3_TABLE_H1D  : "San Francisco International Airport",
   BALI_3_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   BALI_3_TABLE_H3D1 : "Airfare",
   BALI_3_TABLE_H3D2 : "Accommodations",
   BALI_3_TABLE_H3D3 : "2 days cruise	",
   BALI_3_TABLE_H3D4 : "Professional guide",
   BALI_3_TABLE_H4D1 : "Entrance fees",
   BALI_3_TABLE_H4D2 : "Professional guide",

   BALI_4_TITLE:"Hello to the fairy World.",
   BALI_4_STAY: "6 days 7 nights",
   BALI_4_DESCRIPTION: "",
   BALI_4_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   BALI_4_TITLE:"Discover Bali",
   BALI_4_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   BALI_4_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   BALI_4_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   BALI_4_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   BALI_4_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   BALI_4_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   BALI_4_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   BALI_4_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   BALI_4_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   BALI_4_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   BALI_4_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   BALI_4_TABLE_H2: "DEPARTURE TIME",
   BALI_4_TABLE_H3: "INCLUDED",
   BALI_4_TABLE_H4: "NOT INCLUDED",
   BALI_4_TABLE_H1D  : "San Francisco International Airport",
   BALI_4_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   BALI_4_TABLE_H3D1 : "Airfare",
   BALI_4_TABLE_H3D2 : "Accommodations",
   BALI_4_TABLE_H3D3 : "2 days cruise	",
   BALI_4_TABLE_H3D4 : "Professional guide",
   BALI_4_TABLE_H4D1 : "Entrance fees",
   BALI_4_TABLE_H4D2 : "Professional guide",

   GILIS_1_TITLE:"Hello to the fairy World.",
   GILIS_1_STAY: "6 days 7 nights",
   GILIS_1_DESCRIPTION: "",
   GILIS_1_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   GILIS_1_TITLE:"Discover Bali",
   GILIS_1_STAY:"5 DAYS - 4 NIGHTS",
   GILIS_1_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   GILIS_1_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   GILIS_1_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   GILIS_1_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   GILIS_1_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   GILIS_1_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   GILIS_1_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   GILIS_1_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   GILIS_1_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   GILIS_1_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   GILIS_1_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   GILIS_1_TABLE_H2: "DEPARTURE TIME",
   GILIS_1_TABLE_H3: "INCLUDED",
   GILIS_1_TABLE_H4: "NOT INCLUDED",
   GILIS_1_TABLE_H1D  : "San Francisco International Airport",
   GILIS_1_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   GILIS_1_TABLE_H3D1 : "Airfare",
   GILIS_1_TABLE_H3D2 : "Accommodations",
   GILIS_1_TABLE_H3D3 : "2 days cruise	",
   GILIS_1_TABLE_H3D4 : "Professional guide",
   GILIS_1_TABLE_H4D1 : "Entrance fees",
   GILIS_1_TABLE_H4D2 : "Professional guide",

   GILIS_2_TITLE:"Hello to the fairy World.",
   GILIS_2_STAY: "6 days 7 nights",
   GILIS_2_DESCRIPTION: "",
   GILIS_2_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   GILIS_2_TITLE:"Discover Bali",
   GILIS_2_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   GILIS_2_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   GILIS_2_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   GILIS_2_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   GILIS_2_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   GILIS_2_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   GILIS_2_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   GILIS_2_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   GILIS_2_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   GILIS_2_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   GILIS_2_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   GILIS_2_TABLE_H2: "DEPARTURE TIME",
   GILIS_2_TABLE_H3: "INCLUDED",
   GILIS_2_TABLE_H4: "NOT INCLUDED",
   GILIS_2_TABLE_H1D  : "San Francisco International Airport",
   GILIS_2_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   GILIS_2_TABLE_H3D1 : "Airfare",
   GILIS_2_TABLE_H3D2 : "Accommodations",
   GILIS_2_TABLE_H3D3 : "2 days cruise	",
   GILIS_2_TABLE_H3D4 : "Professional guide",
   GILIS_2_TABLE_H4D1 : "Entrance fees",
   GILIS_2_TABLE_H4D2 : "Professional guide",

   GILIS_3_TITLE:"Hello to the fairy World.",
   GILIS_3_STAY: "6 days 7 nights",
   GILIS_3_DESCRIPTION: "",
   GILIS_3_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   GILIS_3_TITLE:"Discover Bali",
   GILIS_3_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   GILIS_3_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   GILIS_3_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   GILIS_3_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   GILIS_3_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   GILIS_3_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   GILIS_3_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   GILIS_3_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   GILIS_3_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   GILIS_3_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   GILIS_3_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   GILIS_3_TABLE_H2: "DEPARTURE TIME",
   GILIS_3_TABLE_H3: "INCLUDED",
   GILIS_3_TABLE_H4: "NOT INCLUDED",
   GILIS_3_TABLE_H1D  : "San Francisco International Airport",
   GILIS_3_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   GILIS_3_TABLE_H3D1 : "Airfare",
   GILIS_3_TABLE_H3D2 : "Accommodations",
   GILIS_3_TABLE_H3D3 : "2 days cruise	",
   GILIS_3_TABLE_H3D4 : "Professional guide",
   GILIS_3_TABLE_H4D1 : "Entrance fees",
   GILIS_3_TABLE_H4D2 : "Professional guide",

   GILIS_4_TITLE:"Hello to the fairy World.",
   GILIS_4_STAY: "6 days 7 nights",
   GILIS_4_DESCRIPTION: "",
   GILIS_4_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   GILIS_4_TITLE:"Discover Bali",
   GILIS_4_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   GILIS_4_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   GILIS_4_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   GILIS_4_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   GILIS_4_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   GILIS_4_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   GILIS_4_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   GILIS_4_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   GILIS_4_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   GILIS_4_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   GILIS_4_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   GILIS_4_TABLE_H2: "DEPARTURE TIME",
   GILIS_4_TABLE_H3: "INCLUDED",
   GILIS_4_TABLE_H4: "NOT INCLUDED",
   GILIS_4_TABLE_H1D  : "San Francisco International Airport",
   GILIS_4_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   GILIS_4_TABLE_H3D1 : "Airfare",
   GILIS_4_TABLE_H3D2 : "Accommodations",
   GILIS_4_TABLE_H3D3 : "2 days cruise	",
   GILIS_4_TABLE_H3D4 : "Professional guide",
   GILIS_4_TABLE_H4D1 : "Entrance fees",
   GILIS_4_TABLE_H4D2 : "Professional guide",

   LOMBOK_1_TITLE:"Hello to the fairy World.",
   LOMBOK_1_STAY: "6 days 7 nights",
   LOMBOK_1_DESCRIPTION: "",
   LOMBOK_1_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   LOMBOK_1_TITLE:"Discover Bali",
   LOMBOK_1_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   LOMBOK_1_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   LOMBOK_1_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   LOMBOK_1_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   LOMBOK_1_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   LOMBOK_1_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   LOMBOK_1_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   LOMBOK_1_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   LOMBOK_1_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   LOMBOK_1_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   LOMBOK_1_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   LOMBOK_1_TABLE_H2: "DEPARTURE TIME",
   LOMBOK_1_TABLE_H3: "INCLUDED",
   LOMBOK_1_TABLE_H4: "NOT INCLUDED",
   LOMBOK_1_TABLE_H1D  : "San Francisco International Airport",
   LOMBOK_1_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   LOMBOK_1_TABLE_H3D1 : "Airfare",
   LOMBOK_1_TABLE_H3D2 : "Accommodations",
   LOMBOK_1_TABLE_H3D3 : "2 days cruise	",
   LOMBOK_1_TABLE_H3D4 : "Professional guide",
   LOMBOK_1_TABLE_H4D1 : "Entrance fees",
   LOMBOK_1_TABLE_H4D2 : "Professional guide",

   LOMBOK_2_TITLE:"Hello to the fairy World.",
   LOMBOK_2_STAY: "6 days 7 nights",
   LOMBOK_2_DESCRIPTION: "",
   LOMBOK_2_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   LOMBOK_2_TITLE:"Discover Bali",
   LOMBOK_2_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   LOMBOK_2_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   LOMBOK_2_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   LOMBOK_2_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   LOMBOK_2_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   LOMBOK_2_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   LOMBOK_2_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   LOMBOK_2_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   LOMBOK_2_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   LOMBOK_2_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   LOMBOK_2_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   LOMBOK_2_TABLE_H2: "DEPARTURE TIME",
   LOMBOK_2_TABLE_H3: "INCLUDED",
   LOMBOK_2_TABLE_H4: "NOT INCLUDED",
   LOMBOK_2_TABLE_H1D  : "San Francisco International Airport",
   LOMBOK_2_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   LOMBOK_2_TABLE_H3D1 : "Airfare",
   LOMBOK_2_TABLE_H3D2 : "Accommodations",
   LOMBOK_2_TABLE_H3D3 : "2 days cruise	",
   LOMBOK_2_TABLE_H3D4 : "Professional guide",
   LOMBOK_2_TABLE_H4D1 : "Entrance fees",
   LOMBOK_2_TABLE_H4D2 : "Professional guide",

   LOMBOK_3_TITLE:"Hello to the fairy World.",
   LOMBOK_3_STAY: "6 days 7 nights",
   LOMBOK_3_DESCRIPTION: "",
   LOMBOK_3_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   LOMBOK_3_TITLE:"Discover Bali",
   LOMBOK_3_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   LOMBOK_3_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   LOMBOK_3_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   LOMBOK_3_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   LOMBOK_3_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   LOMBOK_3_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   LOMBOK_3_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   LOMBOK_3_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   LOMBOK_3_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   LOMBOK_3_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   LOMBOK_3_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   LOMBOK_3_TABLE_H2: "DEPARTURE TIME",
   LOMBOK_3_TABLE_H3: "INCLUDED",
   LOMBOK_3_TABLE_H4: "NOT INCLUDED",
   LOMBOK_3_TABLE_H1D  : "San Francisco International Airport",
   LOMBOK_3_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   LOMBOK_3_TABLE_H3D1 : "Airfare",
   LOMBOK_3_TABLE_H3D2 : "Accommodations",
   LOMBOK_3_TABLE_H3D3 : "2 days cruise	",
   LOMBOK_3_TABLE_H3D4 : "Professional guide",
   LOMBOK_3_TABLE_H4D1 : "Entrance fees",
   LOMBOK_3_TABLE_H4D2 : "Professional guide",

   JAKARTA_1_TITLE:"Hello to the fairy World.",
   JAKARTA_1_STAY: "6 days 7 nights",
   JAKARTA_1_DESCRIPTION: "",
   JAKARTA_1_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   JAKARTA_1_TITLE:"Discover Bali",
   JAKARTA_1_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   JAKARTA_1_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   JAKARTA_1_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   JAKARTA_1_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   JAKARTA_1_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   JAKARTA_1_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   JAKARTA_1_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   JAKARTA_1_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   JAKARTA_1_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   JAKARTA_1_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   JAKARTA_1_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   JAKARTA_1_TABLE_H2: "DEPARTURE TIME",
   JAKARTA_1_TABLE_H3: "INCLUDED",
   JAKARTA_1_TABLE_H4: "NOT INCLUDED",
   JAKARTA_1_TABLE_H1D  : "San Francisco International Airport",
   JAKARTA_1_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   JAKARTA_1_TABLE_H3D1 : "Airfare",
   JAKARTA_1_TABLE_H3D2 : "Accommodations",
   JAKARTA_1_TABLE_H3D3 : "2 days cruise	",
   JAKARTA_1_TABLE_H3D4 : "Professional guide",
   JAKARTA_1_TABLE_H4D1 : "Entrance fees",
   JAKARTA_1_TABLE_H4D2 : "Professional guide",

   JAKARTA_2_TITLE:"Hello to the fairy World.",
   JAKARTA_2_STAY: "6 days 7 nights",
   JAKARTA_2_DESCRIPTION: "",
   JAKARTA_2_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   JAKARTA_2_TITLE:"Discover Bali",
   JAKARTA_2_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   JAKARTA_2_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   JAKARTA_2_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   JAKARTA_2_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   JAKARTA_2_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   JAKARTA_2_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   JAKARTA_2_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   JAKARTA_2_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   JAKARTA_2_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   JAKARTA_2_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   JAKARTA_2_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   JAKARTA_2_TABLE_H2: "DEPARTURE TIME",
   JAKARTA_2_TABLE_H3: "INCLUDED",
   JAKARTA_2_TABLE_H4: "NOT INCLUDED",
   JAKARTA_2_TABLE_H1D  : "San Francisco International Airport",
   JAKARTA_2_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   JAKARTA_2_TABLE_H3D1 : "Airfare",
   JAKARTA_2_TABLE_H3D2 : "Accommodations",
   JAKARTA_2_TABLE_H3D3 : "2 days cruise	",
   JAKARTA_2_TABLE_H3D4 : "Professional guide",
   JAKARTA_2_TABLE_H4D1 : "Entrance fees",
   JAKARTA_2_TABLE_H4D2 : "Professional guide",

   JAKARTA_3_TITLE:"Hello to the fairy World.",
   JAKARTA_3_STAY: "6 days 7 nights",
   JAKARTA_3_DESCRIPTION: "",
   JAKARTA_3_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   JAKARTA_3_TITLE:"Discover Bali",
   JAKARTA_3_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   JAKARTA_3_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   JAKARTA_3_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   JAKARTA_3_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   JAKARTA_3_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   JAKARTA_3_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   JAKARTA_3_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   JAKARTA_3_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   JAKARTA_3_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   JAKARTA_3_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   JAKARTA_3_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   JAKARTA_3_TABLE_H2: "DEPARTURE TIME",
   JAKARTA_3_TABLE_H3: "INCLUDED",
   JAKARTA_3_TABLE_H4: "NOT INCLUDED",
   JAKARTA_3_TABLE_H1D  : "San Francisco International Airport",
   JAKARTA_3_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   JAKARTA_3_TABLE_H3D1 : "Airfare",
   JAKARTA_3_TABLE_H3D2 : "Accommodations",
   JAKARTA_3_TABLE_H3D3 : "2 days cruise	",
   JAKARTA_3_TABLE_H3D4 : "Professional guide",
   JAKARTA_3_TABLE_H4D1 : "Entrance fees",
   JAKARTA_3_TABLE_H4D2 : "Professional guide",

   PUNCAK_1_TITLE:"Hello to the fairy World.",
   PUNCAK_1_STAY: "6 days 7 nights",
   PUNCAK_1_DESCRIPTION: "",
   PUNCAK_1_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   PUNCAK_1_TITLE:"Discover Bali",
   PUNCAK_1_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   PUNCAK_1_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   PUNCAK_1_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   PUNCAK_1_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   PUNCAK_1_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   PUNCAK_1_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   PUNCAK_1_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   PUNCAK_1_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   PUNCAK_1_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   PUNCAK_1_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   PUNCAK_1_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   PUNCAK_1_TABLE_H2: "DEPARTURE TIME",
   PUNCAK_1_TABLE_H3: "INCLUDED",
   PUNCAK_1_TABLE_H4: "NOT INCLUDED",
   PUNCAK_1_TABLE_H1D  : "San Francisco International Airport",
   PUNCAK_1_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   PUNCAK_1_TABLE_H3D1 : "Airfare",
   PUNCAK_1_TABLE_H3D2 : "Accommodations",
   PUNCAK_1_TABLE_H3D3 : "2 days cruise	",
   PUNCAK_1_TABLE_H3D4 : "Professional guide",
   PUNCAK_1_TABLE_H4D1 : "Entrance fees",
   PUNCAK_1_TABLE_H4D2 : "Professional guide",

   PUNCAK_2_TITLE:"Hello to the fairy World.",
   PUNCAK_2_STAY: "6 days 7 nights",
   PUNCAK_2_DESCRIPTION: "",
   PUNCAK_2_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   PUNCAK_2_TITLE:"Discover Bali",
   PUNCAK_2_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   PUNCAK_2_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   PUNCAK_2_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   PUNCAK_2_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   PUNCAK_2_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   PUNCAK_2_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   PUNCAK_2_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   PUNCAK_2_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   PUNCAK_2_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   PUNCAK_2_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   PUNCAK_2_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   PUNCAK_2_TABLE_H2: "DEPARTURE TIME",
   PUNCAK_2_TABLE_H3: "INCLUDED",
   PUNCAK_2_TABLE_H4: "NOT INCLUDED",
   PUNCAK_2_TABLE_H1D  : "San Francisco International Airport",
   PUNCAK_2_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   PUNCAK_2_TABLE_H3D1 : "Airfare",
   PUNCAK_2_TABLE_H3D2 : "Accommodations",
   PUNCAK_2_TABLE_H3D3 : "2 days cruise	",
   PUNCAK_2_TABLE_H3D4 : "Professional guide",
   PUNCAK_2_TABLE_H4D1 : "Entrance fees",
   PUNCAK_2_TABLE_H4D2 : "Professional guide",

   PUNCAK_3_TITLE:"Hello to the fairy World.",
   PUNCAK_3_STAY: "6 days 7 nights",
   PUNCAK_3_DESCRIPTION: "",
   PUNCAK_3_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   PUNCAK_3_TITLE:"Discover Bali",
   PUNCAK_3_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   PUNCAK_3_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   PUNCAK_3_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   PUNCAK_3_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   PUNCAK_3_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   PUNCAK_3_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   PUNCAK_3_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   PUNCAK_3_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   PUNCAK_3_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   PUNCAK_3_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   PUNCAK_3_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   PUNCAK_3_TABLE_H2: "DEPARTURE TIME",
   PUNCAK_3_TABLE_H3: "INCLUDED",
   PUNCAK_3_TABLE_H4: "NOT INCLUDED",
   PUNCAK_3_TABLE_H1D  : "San Francisco International Airport",
   PUNCAK_3_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   PUNCAK_3_TABLE_H3D1 : "Airfare",
   PUNCAK_3_TABLE_H3D2 : "Accommodations",
   PUNCAK_3_TABLE_H3D3 : "2 days cruise	",
   PUNCAK_3_TABLE_H3D4 : "Professional guide",
   PUNCAK_3_TABLE_H4D1 : "Entrance fees",
   PUNCAK_3_TABLE_H4D2 : "Professional guide",

   BANDUNG_1_TITLE:"Hello to the fairy World.",
   BANDUNG_1_STAY: "6 days 7 nights",
   BANDUNG_1_DESCRIPTION: "",
   BANDUNG_1_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   BANDUNG_1_TITLE:"Discover Bali",
   BANDUNG_1_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   BANDUNG_1_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   BANDUNG_1_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   BANDUNG_1_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   BANDUNG_1_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   BANDUNG_1_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   BANDUNG_1_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   BANDUNG_1_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   BANDUNG_1_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   BANDUNG_1_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   BANDUNG_1_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   BANDUNG_1_TABLE_H2: "DEPARTURE TIME",
   BANDUNG_1_TABLE_H3: "INCLUDED",
   BANDUNG_1_TABLE_H4: "NOT INCLUDED",
   BANDUNG_1_TABLE_H1D  : "San Francisco International Airport",
   BANDUNG_1_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   BANDUNG_1_TABLE_H3D1 : "Airfare",
   BANDUNG_1_TABLE_H3D2 : "Accommodations",
   BANDUNG_1_TABLE_H3D3 : "2 days cruise	",
   BANDUNG_1_TABLE_H3D4 : "Professional guide",
   BANDUNG_1_TABLE_H4D1 : "Entrance fees",
   BANDUNG_1_TABLE_H4D2 : "Professional guide",

   BANDUNG_2_TITLE:"Hello to the fairy World.",
   BANDUNG_2_STAY: "6 days 7 nights",
   BANDUNG_2_DESCRIPTION: "",
   BANDUNG_2_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   BANDUNG_2_TITLE:"Discover Bali",
   BANDUNG_2_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   BANDUNG_2_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   BANDUNG_2_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   BANDUNG_2_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   BANDUNG_2_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   BANDUNG_2_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   BANDUNG_2_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   BANDUNG_2_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   BANDUNG_2_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   BANDUNG_2_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   BANDUNG_2_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   BANDUNG_2_TABLE_H2: "DEPARTURE TIME",
   BANDUNG_2_TABLE_H3: "INCLUDED",
   BANDUNG_2_TABLE_H4: "NOT INCLUDED",
   BANDUNG_2_TABLE_H1D  : "San Francisco International Airport",
   BANDUNG_2_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   BANDUNG_2_TABLE_H3D1 : "Airfare",
   BANDUNG_2_TABLE_H3D2 : "Accommodations",
   BANDUNG_2_TABLE_H3D3 : "2 days cruise	",
   BANDUNG_2_TABLE_H3D4 : "Professional guide",
   BANDUNG_2_TABLE_H4D1 : "Entrance fees",
   BANDUNG_2_TABLE_H4D2 : "Professional guide",

   BANDUNG_3_TITLE:"Hello to the fairy World.",
   BANDUNG_3_STAY: "6 days 7 nights",
   BANDUNG_3_DESCRIPTION: "",
   BANDUNG_3_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   BANDUNG_3_TITLE:"Discover Bali",
   BANDUNG_3_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   BANDUNG_3_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   BANDUNG_3_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   BANDUNG_3_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   BANDUNG_3_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   BANDUNG_3_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   BANDUNG_3_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   BANDUNG_3_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   BANDUNG_3_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   BANDUNG_3_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   BANDUNG_3_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   BANDUNG_3_TABLE_H2: "DEPARTURE TIME",
   BANDUNG_3_TABLE_H3: "INCLUDED",
   BANDUNG_3_TABLE_H4: "NOT INCLUDED",
   BANDUNG_3_TABLE_H1D  : "San Francisco International Airport",
   BANDUNG_3_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   BANDUNG_3_TABLE_H3D1 : "Airfare",
   BANDUNG_3_TABLE_H3D2 : "Accommodations",
   BANDUNG_3_TABLE_H3D3 : "2 days cruise	",
   BANDUNG_3_TABLE_H3D4 : "Professional guide",
   BANDUNG_3_TABLE_H4D1 : "Entrance fees",
   BANDUNG_3_TABLE_H4D2 : "Professional guide",

   KOMODO_1_TITLE:"Hello to the fairy World.",
   KOMODO_1_STAY: "6 days 7 nights",
   KOMODO_1_DESCRIPTION: "",
   KOMODO_1_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   KOMODO_1_TITLE:"Discover Bali",
   KOMODO_1_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   KOMODO_1_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   KOMODO_1_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   KOMODO_1_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   KOMODO_1_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   KOMODO_1_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   KOMODO_1_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   KOMODO_1_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   KOMODO_1_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   KOMODO_1_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   KOMODO_1_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   KOMODO_1_TABLE_H2: "DEPARTURE TIME",
   KOMODO_1_TABLE_H3: "INCLUDED",
   KOMODO_1_TABLE_H4: "NOT INCLUDED",
   KOMODO_1_TABLE_H1D  : "San Francisco International Airport",
   KOMODO_1_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   KOMODO_1_TABLE_H3D1 : "Airfare",
   KOMODO_1_TABLE_H3D2 : "Accommodations",
   KOMODO_1_TABLE_H3D3 : "2 days cruise	",
   KOMODO_1_TABLE_H3D4 : "Professional guide",
   KOMODO_1_TABLE_H4D1 : "Entrance fees",
   KOMODO_1_TABLE_H4D2 : "Professional guide",

   KOMODO_2_TITLE:"Hello to the fairy World.",
   KOMODO_2_STAY: "6 days 7 nights",
   KOMODO_2_DESCRIPTION: "",
   KOMODO_2_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   KOMODO_2_TITLE:"Discover Bali",
   KOMODO_2_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   KOMODO_2_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   KOMODO_2_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   KOMODO_2_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   KOMODO_2_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   KOMODO_2_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   KOMODO_2_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   KOMODO_2_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   KOMODO_2_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   KOMODO_2_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   KOMODO_2_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   KOMODO_2_TABLE_H2: "DEPARTURE TIME",
   KOMODO_2_TABLE_H3: "INCLUDED",
   KOMODO_2_TABLE_H4: "NOT INCLUDED",
   KOMODO_2_TABLE_H1D  : "San Francisco International Airport",
   KOMODO_2_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   KOMODO_2_TABLE_H3D1 : "Airfare",
   KOMODO_2_TABLE_H3D2 : "Accommodations",
   KOMODO_2_TABLE_H3D3 : "2 days cruise	",
   KOMODO_2_TABLE_H3D4 : "Professional guide",
   KOMODO_2_TABLE_H4D1 : "Entrance fees",
   KOMODO_2_TABLE_H4D2 : "Professional guide",

   KOMODO_3_TITLE:"Hello to the fairy World.",
   KOMODO_3_STAY: "6 days 7 nights",
   KOMODO_3_DESCRIPTION: "",
   KOMODO_3_DETAIL:"to the vast place where no one can detect the benifit of this economy",
   KOMODO_3_TITLE:"Discover Bali",
   KOMODO_3_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
   KOMODO_3_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
   KOMODO_3_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
   KOMODO_3_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
   KOMODO_3_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
   KOMODO_3_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
   KOMODO_3_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
   KOMODO_3_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
   KOMODO_3_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   KOMODO_3_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
   KOMODO_3_TABLE_H1: "DEPARTURE/RETURN LOCATION",
   KOMODO_3_TABLE_H2: "DEPARTURE TIME",
   KOMODO_3_TABLE_H3: "INCLUDED",
   KOMODO_3_TABLE_H4: "NOT INCLUDED",
   KOMODO_3_TABLE_H1D  : "San Francisco International Airport",
   KOMODO_3_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
   KOMODO_3_TABLE_H3D1 : "Airfare",
   KOMODO_3_TABLE_H3D2 : "Accommodations",
   KOMODO_3_TABLE_H3D3 : "2 days cruise	",
   KOMODO_3_TABLE_H3D4 : "Professional guide",
   KOMODO_3_TABLE_H4D1 : "Entrance fees",
   KOMODO_3_TABLE_H4D2 : "Professional guide",
}

export const ArabicLocale = {

    QUESTION: "Question",
    HAVEAQUESTION:"HAVE A QUESTION?",
    MAILSENTMESSAGE:"Thank you for your email, we will contact you soon..",
    BABYLONHOLIDAYS: "بابيلون للسياحة والسفر",
    BABYLON: "Babylon",
    HOLIDAYS:"Holidays",
    HANDPICKHOTEL: "Handpicked Hotel",
    WORLDCLASSSERVICE: "World Class Service",
    BESTPRICEGURANTEE : "Best Price Guarantee",
    WHYCHOOSEUS :"WHY CHOOSE US",
    HOME: "الصفحة الرئيسية",
    TOURS: "جولات",
    SERVICES: "خدمات",
    CONTACTUS:"اتصل بنا",
    INDIVIDUAL:"فرد",
    HONEYMOON:"شهر العسل",
    GROUP:"مجموعة",
    DISCOVERTHEBEAUTY:"اكتشف الجمال",
    OF:"من",
    BALI:"بالي",
    BOOKATOUR:"حجز جولة",
    OURTOUR:"جولتنا",
    ATTRACTIONSINBALI:"الجذب السياحي في بالي",
    FORMNAME:"اسم",
    FORMEMAIL:"البريد الإلكتروني",
    FORMSUBJECT:"موضوع",
    FORMMESSAGE:"رسالة",
    FORMSUBMIT:"خضع",
    WHEREDOYOUWANTTOSTAY:"أين تريد أن تبقى؟",
    HOTEL:"الفندق",
    VILLA:"فيلا",
    FIVESTAR:"5 نجوم",
    FOURSTAR:"4 نجوم",
    THREESTAR:"3 نجوم",
    GROUPTOURS:"جولات المجموعة",
    NOOFDAYS:"# أيام",
    NOOFPERSONS:"عدد الأشخاص",
    WHENDOYOUWANTTOTRAVEL:"عندما تريد السفر؟",
    FROM:"من عند",
    TO:"إلى",
    CONACTINFORMATION:"معلومات الاتصال",
    PHONENUMBER:"هاتف #",
    HONEYMOONTOURS:" جولات شهر العسل",
    STAYATHOTEL:"البقاء في فندق",
    SEEDETAILS:"انظر التفاصيل",
    STANDARD:"اساسي",
    PREMIUM:"علاوة",
    LUXURY:"ترف",
    STAYATVILLA:"البقاء في فيلا",
    INDIVIDUALTOURS:"جولات فردية",
    HIGHLIGHTS:"يسلط الضوء",
    HONEYMOONSUITAT5STARHOTEL:"جناح شهر العسل في فندق 5 نجوم",
    DAYS7NIGHTS6:"7 أيام 6 ليالي",
    BREAKFASTDINNER:"وجبة الإفطار & العشاء",
    COMFORTABLECARWITHDRIVER:"سيارة مريحة مع سائق",
    TRANSPORT:"المواصلات",
    BOOKNOW:"احجز الآن",
    ENQUIRENOW:"استفسر الان",
    ADDRESS:"عنوان",
    PHONE:"هاتف",
    LANGUAGE:"Language",
    ARABIC:"عربى",
    ENGLISH:"الإنجليزية",
    INDONESIA:"أندونيسيا",
    GILIS:"جيليس",
    LOMBOK:"لومبوك",
    JAKARTA:"جاكرتا",
    PUNCAK:"بونكاك",
    DISTINCTION:"تميز",
    DESTINATIONS:"تميز",
    CATEGORY:"الفئة",
    BALITOORS:"BALI TOURS",
    BANDUNGTOORS:"BANDUNG TOURS",
    GILISTOORS:"GILIS TOURS",
    JAKARTATOORS:"JAKARTA TOURS",
    KOMODOTOORS:"KOMODO TOURS",
    LOMBOKTOORS:"LOMBOK TOURS",
    PUNCAKTOORS:"PUNCAK TOURS",

    SCROLLDOWN: "Scroll",


   /***************************************INDIVIDUAL PAGE *****************************************************/
    INDIVIDUAL_TITLE:"Discover Bali",
    INDIVIDUAL_STAY:"5 DAYS - 4 NIGHTS",
    INIDVIDUAL_CAEGORY_TEXT:"ESCORTED TOUR, RAIL TOUR",
    INIDIVIDUAL_DESCRIPTION_TEXT_1:"Mattis interdum nunc massa. Velit. Nonummy penatibus luctus. Aliquam. Massa aptent senectus elementum taciti.Id sodales morbi felis eu mus auctor ullamcorper. Litora. In nostra tempus, habitant. Nam tristique.",
    INIDIVIDUAL_DESCRIPTION_TEXT_2:"Felis venenatis metus placerat taciti malesuada ultricies bibendum nunc hymenaeos orci erat mollis pretium ligula ligulamus pellentesque urna. Sagittis bibendum justo congue facilisi. Aliquam potenti sagittis etiam facilisis vehicula. Id.",
    INIDIVIDUAL_DESCRIPTION_TEXT_3:"Ridiculus sociis dui eu vivamus tempor justo diam aliquam. Ipsum nunc purus, pede sed placerat sit habitasse potenti eleifend magna mus sociosqu hymenaeos cras metus mi donec tortor nisi leo dignissim turpis sit torquent.",
    INIDIVIDUAL_DESCRIPTION_TEXT_4:"Potenti mattis ad mollis eleifend Phasellus adipiscing ullamcorper interdum faucibus orci litora ornare aliquam. Ligula feugiat scelerisque. Molestie. Facilisi hac.",
    INDIVIDUAL_DAY_1_DEP_1  : "Ornare proin neque tempus cubilia cubilia blandit netus.",
    INDIVIDUAL_DAY_1_DEP_2  : "Maecenas massa. Fermentum.",
    INDIVIDUAL_DAY_1_DEP_P1 : "Pretium vitae tempus sem enim enim.",
    INDIVIDUAL_DAY_1_DEP_P2 : "Tempus, leo, taciti augue aliquam hendrerit.",
    INDIVIDUAL_DAY_1_DEP_P3 : "Accumsan pharetra eros justo augue posuere felis elit cras montes fames.",
    INDIVIDUAL_DAY_1_DEP_P4 : "Vulputate dictumst egestas etiam dictum varius.",
    INDIVIDUAL_DAY_2_DEP_1  : "Tortor elementum egestas metus potenti habitasse tempus natoque senectus commodo rutrum quisque fermentum. Nisi velit primis dapibus odio consequat facilisi sollicitudin porta nulla tellus sagittis platea tempor sed parturient convallis consectetuer Vulputate curae; pharetra." ,
    INDIVIDUAL_DAY_3_DEP_1  : "Fusce sagittis viverra lorem proin porttitor conubia risus vivamus. Mollis. Luctus curabitur porta nibh penatibus aliquet nec conubia magnis semper, sem feugiat scelerisque molestie. Nibh proin dapibus phasellus lacus. Facilisi.",
    INDIVIDUAL_DAY_4_DEP_1  : "Pretium consequat, facilisis sem in malesuada sodales et ipsum proin eleifend tincidunt, urna morbi metus quisque. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
    INDIVIDUAL_DAY_5_DEP_1  : "Egestas maecenas hac nullam integer at. Lacinia habitasse ridiculus sapien platea a cursus hendrerit tempor facilisi orci at tempor, senectus.",
    INDIVIDUAL_TABLE_H1: "DEPARTURE/RETURN LOCATION",
    INDIVIDUAL_TABLE_H2: "DEPARTURE TIME",
    INDIVIDUAL_TABLE_H3: "INCLUDED",
    INDIVIDUAL_TABLE_H4: "NOT INCLUDED",
    INDIVIDUAL_TABLE_H1D  : "San Francisco International Airport",
    INDIVIDUAL_TABLE_H2D  : "Please arrive at least 2 hours before the flight.",
    INDIVIDUAL_TABLE_H3D1 : "Airfare",
    INDIVIDUAL_TABLE_H3D2 : "Accommodations",
    INDIVIDUAL_TABLE_H3D3 : "2 days cruise	",
    INDIVIDUAL_TABLE_H3D4 : "Professional guide",
    INDIVIDUAL_TABLE_H4D1 : "Entrance fees",
    INDIVIDUAL_TABLE_H4D2 : "Professional guide",

   /************************************************************************************************************/

   BALI_1_TITLE:"Hello to the fairy World.",
   BALI_1_STAY: "6 days 7 nights",
   BALI_1_DESCRIPTION: "",
   BALI_1_DETAIL:"سيارة مريحة مع سائق",
   BALI_2_TITLE:"Hello to the fairy World.",
   BALI_2_STAY: "6 days 7 nights",
   BALI_2_DESCRIPTION: "",
   BALI_2_DETAIL:"سيارة مريحة مع سائق",
   BALI_3_TITLE:"Hello to the fairy World.",
   BALI_3_STAY: "6 days 7 nights",
   BALI_3_DESCRIPTION: "",
   BALI_3_DETAIL:"سيارة مريحة مع سائق",
   BALI_4_TITLE:"Hello to the fairy World.",
   BALI_4_STAY: "6 days 7 nights",
   BALI_4_DESCRIPTION: "",
   BALI_4_DETAIL:"سيارة مريحة مع سائق",
   LOMBOK_1_TITLE:"Hello to the fairy World.",
   LOMBOK_1_STAY: "6 days 7 nights",
   LOMBOK_1_DESCRIPTION: "",
   LOMBOK_1_DETAIL:"سيارة مريحة مع سائق",
   LOMBOK_2_TITLE:"Hello to the fairy World.",
   LOMBOK_2_STAY: "6 days 7 nights",
   LOMBOK_2_DESCRIPTION: "",
   LOMBOK_2_DETAIL:"سيارة مريحة مع سائق",
   LOMBOK_3_TITLE:"Hello to the fairy World.",
   LOMBOK_3_STAY: "6 days 7 nights",
   LOMBOK_3_DESCRIPTION: "",
   LOMBOK_3_DETAIL:"سيارة مريحة مع سائق",
   JAKARTA_1_TITLE:"Hello to the fairy World.",
   JAKARTA_1_STAY: "6 days 7 nights",
   JAKARTA_1_DESCRIPTION: "",
   JAKARTA_1_DETAIL:"سيارة مريحة مع سائق",
   JAKARTA_2_TITLE:"Hello to the fairy World.",
   JAKARTA_2_STAY: "6 days 7 nights",
   JAKARTA_2_DESCRIPTION: "",
   JAKARTA_2_DETAIL:"سيارة مريحة مع سائق",
   JAKARTA_3_TITLE:"Hello to the fairy World.",
   JAKARTA_3_STAY: "6 days 7 nights",
   JAKARTA_3_DESCRIPTION: "",
   JAKARTA_3_DETAIL:"سيارة مريحة مع سائق",
   PUNCAK_1_TITLE:"Hello to the fairy World.",
   PUNCAK_1_STAY: "6 days 7 nights",
   PUNCAK_1_DESCRIPTION: "",
   PUNCAK_1_DETAIL:"سيارة مريحة مع سائق",
   PUNCAK_2_TITLE:"Hello to the fairy World.",
   PUNCAK_2_STAY: "6 days 7 nights",
   PUNCAK_2_DESCRIPTION: "",
   PUNCAK_2_DETAIL:"سيارة مريحة مع سائق",
   PUNCAK_3_TITLE:"Hello to the fairy World.",
   PUNCAK_3_STAY: "6 days 7 nights",
   PUNCAK_3_DESCRIPTION: "",
   PUNCAK_3_DETAIL:"سيارة مريحة مع سائق",

   BANDUNG_1_TITLE:"Hello to the fairy World.",
   BANDUNG_1_STAY: "6 days 7 nights",
   BANDUNG_1_DESCRIPTION: "",
   BANDUNG_1_DETAIL:"سيارة مريحة مع سائق",
   BANDUNG_2_TITLE:"Hello to the fairy World.",
   BANDUNG_2_STAY: "6 days 7 nights",
   BANDUNG_2_DESCRIPTION: "",
   BANDUNG_2_DETAIL:"سيارة مريحة مع سائق",
   BANDUNG_3_TITLE:"Hello to the fairy World.",
   BANDUNG_3_STAY: "6 days 7 nights",
   BANDUNG_3_DESCRIPTION: "",
   BANDUNG_3_DETAIL:"سيارة مريحة مع سائق",

   KOMODO_1_TITLE:"Hello to the fairy World.",
   KOMODO_1_STAY: "6 days 7 nights",
   KOMODO_1_DESCRIPTION: "",
   KOMODO_1_DETAIL:"سيارة مريحة مع سائق",
   KOMODO_2_TITLE:"Hello to the fairy World.",
   KOMODO_2_STAY: "6 days 7 nights",
   KOMODO_2_DESCRIPTION: "",
   KOMODO_2_DETAIL:"سيارة مريحة مع سائق",
   KOMODO_3_TITLE:"Hello to the fairy World.",
   KOMODO_3_STAY: "6 days 7 nights",
   KOMODO_3_DESCRIPTION: "",
   KOMODO_3_DETAIL:"سيارة مريحة مع سائق",
}
